import Thumbnail from "./images/logo.png"
export const DUMMY_POSTS=[
    {
        id:"1",
        thumbnail:Thumbnail,
        category:"education",
        title:"bvisghoaeijvb",
        desc:"nijgojsdvnjhfowekpof",
        authorID:1
    },
    {
        id:"2",
        thumbnail:Thumbnail,
        category:"busines",
        title:"bvisghoaeijvb",
        desc:"nijgojsdvnjhfowekpof",
        authorID:2
    },
    {
        id:"3",
        thumbnail:Thumbnail,
        category:"education",
        title:"bvisghoaeijvb",
        desc:"nijgojsdvnjhfowekpof",
        authorID:3
    },
    {
        id:"4",
        thumbnail:Thumbnail,
        category:"education",
        title:"bvisghoaeijvb",
        desc:"nijgojsdvnjhfowekpof",
        authorID:4
    },
    {
        id:"5",
        thumbnail:Thumbnail,
        category:"education",
        title:"bvisghoaeijvb",
        desc:"nijgojsdvnjhfowekpof",
        authorID:5
    },
    ,
    {
        id:"6",
        thumbnail:Thumbnail,
        category:"education",
        title:"bvisghoaeijvb",
        desc:"nijgojsdvnjhfowekpof",
        authorID:6
    },
]